FileAction:
  tmux.conf:
    hidden: true
    source: ../common
    command: ln -s
    destination: $HOME
  tmux.theme.sh:
    hidden: true
    source: ../common
    command: ln -s
    destination: $HOME
  tmux resurrect:
    hidden: true
    source: ../common
    command: ln -s
    destination: $HOME
